# For a detailed guide to building and testing on iOS, read the docs:
# https://circleci.com/docs/2.0/testing-ios/

version: 2.1

jobs:
  build:

    macos:
      xcode: 11.5.0 # Specify the Xcode version to use

    steps:
      - checkout
      - run: xcrun simctl list
      - run: sudo gem install cocoapods
      - run: pod install # Install CocoaPods dependencies
      - run: fastlane gym # Run tests using Fastlane
