name: Build

on:
  push:
    branches: [ master ]

jobs:


  test-workspace:

    runs-on: macos-latest
    strategy:
      matrix:
        destination:
          - platform=iOS Simulator,OS=latest,name=iPhone 11
        action: [ build ]
        use-xcpretty: [ true, false ]
    steps:
      - run: sudo xcode-select -s /Applications/Xcode_11.4.app/Contents/Developer
      - uses: actions/checkout@v2
      - uses: sersoft-gmbh/xcodebuild-action@master
        with:
          workspace:  Ghosting Connector.xcworkspace
          scheme: Ghosting Connector
          destination: ${{matrix.destination}}
          skip-testing: ${{matrix.skip-testing}}
          action: ${{matrix.action}}
          use-xcpretty: ${{matrix.use-xcpretty}}
