# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  test-workspace:
    runs-on: macos-latest
    strategy:
      matrix:
        destination:
          - platform=iOS Simulator,id=765CEAC1-8A25-41A4-A35A-FE5B239CA466
        action: [ build ]
        use-xcpretty: [ true, false ]
    steps:
      - run: xcrun simctl list && sudo xcode-select -s /Applications/Xcode_11.4.app/Contents/Developer 
      - uses: actions/checkout@v2
      - uses: sersoft-gmbh/xcodebuild-action@master
        with:
          workspace: Ghosting Connector.xcworkspace
          scheme: Ghosting Connector
          destination: ${{matrix.destination}}
          skip-testing: ${{matrix.skip-testing}}
          action: ${{matrix.action}}
          use-xcpretty: ${{matrix.use-xcpretty}}

  
