name: Master Deploy

on:
  push:
    branches: [ master ]

jobs:
  deploy-action-code:
    runs-on: ubuntu-latest
    steps:
      - name: Install depenedencies
        run: sudo npm i -g @zeit/ncc typescript
      - uses: actions/checkout@v2
      - name: Generate action code
        run: npm run deploy
      - name: Configure repository
        run: |
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
      - name: Commit changes
        run: |
          if ! git diff --exit-code; then
            git add .
            git commit -m "[AUTO] Update generated code"
            git push
          fi
  
  test-workspace:
    needs: deploy-action-code
    runs-on: macos-latest
    strategy:
      matrix:
        destination:
          - platform=macOS
          - platform=iOS Simulator,OS=latest,name=iPhone 11
        action: [ build ]
        use-xcpretty: [ true, false ]
        include:
          - destination: platform=iOS Simulator,OS=latest,name=iPhone 11
            skip-testing: ''
            action: build
            use-xcpretty: true
        
    steps:
      - run: sudo xcode-select -s /Applications/Xcode_11.4.app/Contents/Developer
      - uses: actions/checkout@v2
      - uses: sersoft-gmbh/xcodebuild-action@master
        with:
          workspace:  Ghosting COnnector.xcworkspace
          scheme: Ghosting Connector
          destination: ${{matrix.destination}}
          skip-testing: ${{matrix.skip-testing}}
          action: ${{matrix.action}}
          use-xcpretty: ${{matrix.use-xcpretty}}
      

  
