name: Swift

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: xcodebuild clean build -workspace Ghosting\ Connector.xcworkspace -scheme Ghosting\ Connector CODE_SIGN_IDENTITY="iPhone Developer" CODE_SIGNING_REQUIRED=NO
